import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Physical AI Foundations',
      items: [{type: 'autogenerated', dirName: 'physical-ai-foundations'}],
    },
    {
      type: 'category',
      label: 'ROS 2 Fundamentals and Gazebo Simulation',
      items: [{type: 'autogenerated', dirName: 'ros2-gazebo-simulation'}],
    },
    {
      type: 'category',
      label: 'Advanced Robotics Simulation',
      items: [{type: 'autogenerated', dirName: 'advanced-robotics-simulation'}],
    },
    {
      type: 'category',
      label: 'Humanoid Robotics, VLA, and Conversational AI',
      items: [{type: 'autogenerated', dirName: 'humanoid-vla-conversational-ai'}],
    },
  ],
};

export default sidebars;
